[package]
name = "dining_philosophers"
version = "0.1.0"
authors = ["Toshiaki Yokoda <t.yokoda@gvc.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
